>PDB:5zj3:B TEXTILININ-1, A KUNITZ-TYPE SERINE PROTEASE INHIBI
-----kdrPd-fC-ELPADT--GP-CRvRFPSFYYNPDEKKCLEFIYGgCEG-NANNFITKEECESTCa-
--

>PDB:4u32:X HUMAN MESOTRYPSIN COMPLEXED WITH HAI-2 KUNITZ DOMA
--------Hd-fC-LVSKVV--GR-CRaSMPRWWYNVTDGSCQLFVYGgCDG-NSNNYLTKEECLKKC--
--

>PDB:4dtg:K HEMOSTATIC EFFECT OF A MONOCLONAL ANTIBODY MAB 202
------ekPd-fC-FLEEDP--GI-CRgYITRYFYNNQTKQCERFKYGgCLG-NMNNFETLEECKNICed
gh

>PDB:6q61:A PORE-MODULATING TOXINS EXPLOIT INHERENT SLOW INACT
------drPs-lC-DLPADS--GS-GTkAEKRIYYNSARKQCLRFDYTgQGG-NENNFRRTYDCARTCly
t-

>PDB:1zjd:B CRYSTAL STRUCTURE OF THE CATALYTIC DOMAIN OF COAGU
-------eV---C-SEQAET--GP-CRaMISRWYFDVTEGKCAPFFYGgCGG-NRNNFDTEEYCMAVCgs
ai

>PDB:5yv7:A RACEMIC X-RAY STRUCTURE OF CALCICLUDINE
-----wqpPw-yC-KEPVRI--GS-CKkQFSSFYFKWTAKKCLPFLFSgCGG-NANRFQTIGECRKKClg
k-

>PDB:1dtx:A CRYSTAL STRUCTURE OF ALPHA-DENDROTOXIN FROM THE GR
-----eprRk-lC-ILHRNP--GR-CYdKIPAFYYNQKKKQCERFDWSgCGG-NSNRFKTIEECRRTCig
--

>PDB:1kth:A THE ANISOTROPIC REFINEMENT OF KUNITZ TYPE DOMAIN C
-------eTd-iC-KLPKDE--GT-CRdFILKWYYDPNTKSCARFWYGgCGG-NENKFGSQKECEKVCap
v-

>PDB:4bqd:B KD1 OF HUMAN TFPI IN COMPLEX WITH A SYNTHETIC PEPT
elpplklmHs-fC-AFKADD--GP-CKaIMKRFFFNIFTRQCEEFIYGgCEG-NQNRFESLEECKKMCtr
d-

>PDB:3m7q:B CRYSTAL STRUCTURE OF RECOMBINANT KUNITZ TYPE SERIN
-----eaeAs-iC-SEPKKV--GR-CKgYFPRFYFDSETGKCTPFIYGgCGG-NGNNFETLHQCRAICra
lg

>PDB:1zr0:B CRYSTAL STRUCTURE OF KUNITZ DOMAIN 1 OF TISSUE FAC
----ptgnNaeiC-LLPLDY--GP-CRaLLLRYYYDRYTQSCRQFLYGgCEG-NANNFYTWEACDDACwr
ie

>PDB:4u30:X HUMAN MESOTRYPSIN COMPLEXED WITH BIKUNIN KUNITZ DO
--------A---CaNLPIVR--GP-CRaFIQLWAFDAVKGKCVLFPYGgCQG-NGNKFYSEKECREYCg-
--

>PDB:4ntx:B STRUCTURE OF ACID-SENSING ION CHANNEL IN COMPLEX W
-----eirPa-fC-YEDPPFfqKC-GA-FVDSYYFNRSRITCVHFFYG-QCDvNQNHFTTMSECNRVChg
--

>PDB:1yc0:I SHORT FORM HGFA WITH FIRST KUNITZ DOMAIN FROM HAI-
qhqhqmhqTedyC-LASNKV--GR-CRgSFPRWYYDPTEQICKSFVYGgCLG-NKNNYLREEECILACrg
v-

>PDB:1bun:B STRUCTURE OF BETA2-BUNGAROTOXIN: POTASSIUM CHANNEL
------rkRhpdC-DKPPDT--KIcQT-VVRAFYYKPSAKRCVQFRYG-GCNgNGNHFKSDHLCRCECle
yr
